baseURL = 'https://whois.julien.io/'
languageCode = 'en-us'
title = 'Who is Julien Mousqueton'

theme = "awesome-identity"

# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true

## Profile Configurations
[params.profile]
  portrait = "/images/julien.jpeg"
  firstname = "Julien"
  lastname = "Mousqueton"
  title = "CTO @ Computacenter"
  bio = """Julien Mousqueton has been a security enthusiast for a long time. He has worked in the security field for more than a decade. During this time, Julien has covered operations as well as consulting within various industries. He possesses a wide range of skills and experiences that enable him to perform multiple roles.
  """
[params.meta]
  description = "Julien Mousqueton - Chief Technoglist Officer Cyber Security."
  keywords = "CTO, Ransomware, Julien, Mousqueton, Julien Mousqueton, Computacenter, cybersecurity, malware, SOC, CyberSOC, CERT, CSIRT, infrastructure, hacker, engineer, architect"
  images = [
    "/images/profile.jpg"
  ]

[params.contacts]
  email = "julien+public@mousqueton.io"
  github = "jmousqueton"
  twitter = "jmousqueton"
  linkedin = "julienmousqueton"
  keybase = "jmousqueton"
  mastodon = "https://infosec.exchange/@JMousqueton"
  # facebook = "posquit0"
  # stackoverflow = "7919458"
  # instagram = "posquit0.bj"
  # medium = "posquit0"
  # quora = "posquit0"
  # dribbble = "posquit0"
  # behance = "posquit0"
  # vcard = "add.julienmousqueton.fr"

## Footer Configurations
[params.footer]
  copyright = "© 2019-2023 Julien Mousqueton[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = false

[params.crisp]
  websiteId = "701b0df5-7b50-48e2-af1f-b75d96bc1ae1"
  # Change the chatbox color theme
  color = "blue"
  # Reverse the chatbox position
  reversePosition = false
  # Hide chatbox on mobile devices
  hideOnMobile = false
  # Hide chatbox on support away
  hideOnAway = false
  # Hide chatbox on vacation
  hideVacation = false

## Actions Configurations
[[params.actions]]
  name = "Review My CV"
  url = "https://cv.julien.io"
[[params.actions]]
  name = "Read my blog"
  url = "https://www.julien.io"


## Privacy Configurations (GDPR)
[privacy]
  [privacy.googleAnalytics]
    disable = false
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = false
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = false
    # Disable the use of Cookies and use Session Storage to Store the GA Client ID
    useSessionStorage = false
